# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(181A1D)
$foreground = rgb(B8CAD2)
$color0 = rgb(3E4144)
$color1 = rgb(0A1823)
$color2 = rgb(0B2332)
$color3 = rgb(214352)
$color4 = rgb(464169)
$color5 = rgb(264D5E)
$color6 = rgb(264D5E)
$color7 = rgb(91ABB6)
$color8 = rgb(65777F)
$color9 = rgb(0E202E)
$color10 = rgb(0E2F43)
$color11 = rgb(2C596D)
$color12 = rgb(5E578C)
$color13 = rgb(33677D)
$color14 = rgb(33677D)
$color15 = rgb(91ABB6)
