# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B8CAD2
background         #181A1D
cursor             #637C8A

active_tab_foreground     #181A1D
active_tab_background     #B8CAD2
inactive_tab_foreground   #B8CAD2
inactive_tab_background   #181A1D

active_border_color   #B8CAD2
inactive_border_color #181A1D
bell_border_color     #0A1823

color0      #3E4144
color1		#0A1823
color2		#0B2332
color3		#214352
color4		#464169
color5		#264D5E
color6		#264D5E
color7		#91ABB6
color8		#65777F
color9		#0E202E
color10		#0E2F43
color11		#2C596D
color12		#5E578C
color13		#33677D
color14		#33677D
color15		#91ABB6
