local colors = {
  -- PATCH_OPEN
  Normal = {fg = "#000000", bg = "#FFFFEB"},
  Boolean = {link = "Normal"},
  Character = {link = "Normal"},
  Comment = {link = "Normal"},
  Conditional = {link = "Normal"},
  Constant = {link = "Normal"},
  Debug = {link = "Normal"},
  Define = {link = "Normal"},
  Delimiter = {link = "Normal"},
  Directory = {link = "Normal"},
  Error = {link = "Normal"},
  Exception = {link = "Normal"},
  Float = {link = "Normal"},
  Function = {link = "Normal"},
  Identifier = {link = "Normal"},
  Ignore = {link = "Normal"},
  Include = {link = "Normal"},
  Keyword = {link = "Normal"},
  Label = {link = "Normal"},
  Macro = {link = "Normal"},
  MsgArea = {link = "Normal"},
  NormalNC = {link = "Normal"},
  Number = {link = "Normal"},
  Operator = {link = "Normal"},
  PreCondit = {link = "Normal"},
  PreProc = {link = "Normal"},
  Repeat = {link = "Normal"},
  Special = {link = "Normal"},
  SpecialChar = {link = "Normal"},
  SpecialComment = {link = "Normal"},
  Statement = {link = "Normal"},
  StorageClass = {link = "Normal"},
  String = {link = "Normal"},
  Structure = {link = "Normal"},
  Tag = {link = "Normal"},
  Title = {link = "Normal"},
  Todo = {link = "Normal"},
  Type = {link = "Normal"},
  Typedef = {link = "Normal"},
  Underlined = {link = "Normal"},
  ["@attribute"] = {link = "Normal"},
  ["@boolean"] = {link = "Normal"},
  ["@character"] = {link = "Normal"},
  ["@comment"] = {link = "Normal"},
  ["@conditional"] = {link = "Normal"},
  ["@constant"] = {link = "Normal"},
  ["@constructor"] = {link = "Normal"},
  ["@exception"] = {link = "Normal"},
  ["@field"] = {link = "Normal"},
  ["@float"] = {link = "Normal"},
  ["@function"] = {link = "Normal"},
  ["@include"] = {link = "Normal"},
  ["@keyword"] = {link = "Normal"},
  ["@label"] = {link = "Normal"},
  ["@markup"] = {link = "Normal"},
  ["@method"] = {link = "Normal"},
  ["@module"] = {link = "Normal"},
  ["@namespace"] = {link = "Normal"},
  ["@number"] = {link = "Normal"},
  ["@operator"] = {link = "Normal"},
  ["@parameter"] = {link = "Normal"},
  ["@preproc"] = {link = "Normal"},
  ["@property"] = {link = "Normal"},
  ["@punctuation"] = {link = "Normal"},
  ["@repeat"] = {link = "Normal"},
  ["@string"] = {link = "Normal"},
  ["@tag"] = {link = "Normal"},
  ["@text"] = {link = "Normal"},
  ["@type"] = {link = "Normal"},
  ["@variable"] = {link = "Normal"},
  ColorColumn = {bg = "#EDEB9C"},
  Conceal = {fg = "#908F4C", bg = "#FFFFEB"},
  CurSearch = {fg = "#000000", bg = "#7B7EC1"},
  IncSearch = {link = "CurSearch"},
  Substitute = {link = "CurSearch"},
  Cursor = {fg = "#FFFFEB", bg = "#000000"},
  CursorIM = {link = "Cursor"},
  TermCursor = {link = "Cursor"},
  lCursor = {link = "Cursor"},
  CursorColumn = {bg = "#FFFFEB"},
  CursorLine = {bg = "#FFFFEB"},
  CursorLineNr = {fg = "#000000", bg = "#FFFFEB", bold = true},
  DiagnosticError = {fg = "#AB6059"},
  DiagnosticFloatingError = {link = "DiagnosticError"},
  DiagnosticSignError = {link = "DiagnosticError"},
  DiagnosticVirtualTextError = {link = "DiagnosticError"},
  DiagnosticHint = {fg = "#638754"},
  DiagnosticFloatingHint = {link = "DiagnosticHint"},
  DiagnosticSignHint = {link = "DiagnosticHint"},
  DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
  DiagnosticInfo = {fg = "#000099"},
  DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
  DiagnosticSignInfo = {link = "DiagnosticInfo"},
  DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
  DiagnosticOk = {fg = "#638754"},
  DiagnosticFloatingOk = {link = "DiagnosticOk"},
  DiagnosticSignOk = {link = "DiagnosticOk"},
  DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
  DiagnosticUnderlineError = {sp = "#AB6059", undercurl = true},
  DiagnosticUnderlineHint = {sp = "#638754", underline = true},
  DiagnosticUnderlineInfo = {sp = "#000099", underline = true},
  DiagnosticUnderlineOk = {sp = "#638754", underline = true},
  DiagnosticUnderlineWarn = {sp = "#908F4C", undercurl = true},
  DiagnosticWarn = {fg = "#908F4C"},
  DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
  DiagnosticSignWarn = {link = "DiagnosticWarn"},
  DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
  EndOfBuffer = {fg = "#FFFFEB", bg = "#FFFFEB"},
  ErrorMsg = {fg = "#AB6059", bg = "#FFFFEB"},
  FloatBorder = {fg = "#7B7EC1", bg = "#FFFFEB"},
  FloatTitle = {fg = "#000000", bg = "#7B7EC1", bold = true},
  FoldColumn = {fg = "#908F4C", bg = "#FFFFEB"},
  Folded = {fg = "#000000", bg = "#EDEB9C"},
  LineNr = {fg = "#908F4C", bg = "#FFFFEB"},
  LineNrAbove = {link = "LineNr"},
  LineNrBelow = {link = "LineNr"},
  LspCodeLens = {fg = "#908F4C", bg = "#FFFFEB"},
  LspCodeLensSeparator = {link = "LspCodeLens"},
  LspReferenceText = {bg = "#EDEB9C"},
  LspReferenceRead = {link = "LspReferenceText"},
  LspReferenceWrite = {link = "LspReferenceText"},
  LspSignatureActiveParameter = {fg = "#000000", bg = "#EDEB9C"},
  MatchParen = {fg = "#000000", bg = "#EDEB9C", bold = true},
  ModeMsg = {fg = "#000000", bg = "#FFFFEB", bold = true},
  MoreMsg = {fg = "#638754", bg = "#FFFFEB"},
  MsgSeparator = {fg = "#7B7EC1", bg = "#F0FEFF"},
  NonText = {fg = "#908F4C", bg = "#FFFFEB"},
  NormalFloat = {fg = "#000000", bg = "#FFFFEB"},
  Pmenu = {fg = "#000000", bg = "#F0FEFF"},
  PmenuKind = {link = "Pmenu"},
  PmenuExtra = {fg = "#908F4C", bg = "#F0FEFF"},
  PmenuSbar = {bg = "#F0FEFF"},
  PmenuSel = {fg = "#000000", bg = "#7B7EC1"},
  PmenuExtraSel = {link = "PmenuSel"},
  PmenuKindSel = {link = "PmenuSel"},
  WildMenu = {link = "PmenuSel"},
  PmenuThumb = {bg = "#7B7EC1"},
  Question = {fg = "#000099", bg = "#FFFFEB"},
  QuickFixLine = {fg = "#000000", bg = "#7B7EC1"},
  Search = {fg = "#000000", bg = "#EDEB9C"},
  SignColumn = {fg = "#000000", bg = "#FFFFEB"},
  SpecialKey = {fg = "#908F4C", bg = "#FFFFEB"},
  SpellBad = {sp = "#AB6059", undercurl = true},
  SpellCap = {sp = "#000099", undercurl = true},
  SpellLocal = {sp = "#638754", undercurl = true},
  SpellRare = {sp = "#908F4C", undercurl = true},
  StatusLine = {fg = "#000000", bg = "#F0FEFF", bold = true},
  StatusLineNC = {fg = "#7B7EC1", bg = "#F0FEFF"},
  TabLine = {fg = "#000000", bg = "#F0FEFF"},
  TabLineFill = {fg = "#7B7EC1", bg = "#F0FEFF"},
  TabLineSel = {fg = "#000000", bg = "#7B7EC1", bold = true},
  Visual = {fg = "#000000", bg = "#EDEB9C"},
  VisualNOS = {link = "Visual"},
  WarningMsg = {fg = "#908F4C", bg = "#FFFFEB"},
  Whitespace = {fg = "#908F4C", bg = "#FFFFEB"},
  WinBar = {fg = "#000000", bg = "#F0FEFF", bold = true},
  WinBarNC = {fg = "#7B7EC1", bg = "#F0FEFF"},
  WinSeparator = {fg = "#7B7EC1", bg = "#FFFFEB"},
  VertSplit = {link = "WinSeparator"},
  -- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.g.colors_name = "acme"

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
