local colors = {
  -- PATCH_OPEN
  Normal = {fg = "#f4decd", bg = "#0f0f0f"},
  Boolean = {link = "Normal"},
  Character = {link = "Normal"},
  Comment = {link = "Normal"},
  Conditional = {link = "Normal"},
  Constant = {link = "Normal"},
  Debug = {link = "Normal"},
  Define = {link = "Normal"},
  Delimiter = {link = "Normal"},
  Directory = {link = "Normal"},
  Error = {link = "Normal"},
  Exception = {link = "Normal"},
  Float = {link = "Normal"},
  Function = {link = "Normal"},
  Identifier = {link = "Normal"},
  Ignore = {link = "Normal"},
  Include = {link = "Normal"},
  Keyword = {link = "Normal"},
  Label = {link = "Normal"},
  Macro = {link = "Normal"},
  MsgArea = {link = "Normal"},
  NormalNC = {link = "Normal"},
  Number = {link = "Normal"},
  Operator = {link = "Normal"},
  PreCondit = {link = "Normal"},
  PreProc = {link = "Normal"},
  Repeat = {link = "Normal"},
  Special = {link = "Normal"},
  SpecialChar = {link = "Normal"},
  SpecialComment = {link = "Normal"},
  Statement = {link = "Normal"},
  StorageClass = {link = "Normal"},
  String = {link = "Normal"},
  Structure = {link = "Normal"},
  Tag = {link = "Normal"},
  Title = {link = "Normal"},
  Todo = {link = "Normal"},
  Type = {link = "Normal"},
  Typedef = {link = "Normal"},
  Underlined = {link = "Normal"},
  ["@attribute"] = {link = "Normal"},
  ["@boolean"] = {link = "Normal"},
  ["@character"] = {link = "Normal"},
  ["@comment"] = {link = "Normal"},
  ["@conditional"] = {link = "Normal"},
  ["@constant"] = {link = "Normal"},
  ["@constructor"] = {link = "Normal"},
  ["@exception"] = {link = "Normal"},
  ["@field"] = {link = "Normal"},
  ["@float"] = {link = "Normal"},
  ["@function"] = {link = "Normal"},
  ["@include"] = {link = "Normal"},
  ["@keyword"] = {link = "Normal"},
  ["@label"] = {link = "Normal"},
  ["@markup"] = {link = "Normal"},
  ["@method"] = {link = "Normal"},
  ["@module"] = {link = "Normal"},
  ["@namespace"] = {link = "Normal"},
  ["@number"] = {link = "Normal"},
  ["@operator"] = {link = "Normal"},
  ["@parameter"] = {link = "Normal"},
  ["@preproc"] = {link = "Normal"},
  ["@property"] = {link = "Normal"},
  ["@punctuation"] = {link = "Normal"},
  ["@repeat"] = {link = "Normal"},
  ["@string"] = {link = "Normal"},
  ["@tag"] = {link = "Normal"},
  ["@text"] = {link = "Normal"},
  ["@type"] = {link = "Normal"},
  ["@variable"] = {link = "Normal"},
  ColorColumn = {bg = "#2b302b"},
  Conceal = {fg = "#6c756f", bg = "#0f0f0f"},
  CurSearch = {fg = "#0f0f0f", bg = "#ef934d"},
  IncSearch = {link = "CurSearch"},
  Substitute = {link = "CurSearch"},
  Cursor = {fg = "#0f0f0f", bg = "#d9cdb5"},
  CursorIM = {link = "Cursor"},
  TermCursor = {link = "Cursor"},
  lCursor = {link = "Cursor"},
  CursorColumn = {bg = "#0f0f0f"},
  CursorLine = {bg = "#0f0f0f"},
  CursorLineNr = {fg = "#f4decd", bg = "#0f0f0f", bold = true},
  DiagnosticError = {fg = "#f16e65"},
  DiagnosticFloatingError = {link = "DiagnosticError"},
  DiagnosticSignError = {link = "DiagnosticError"},
  DiagnosticVirtualTextError = {link = "DiagnosticError"},
  DiagnosticHint = {fg = "#7ec9a3"},
  DiagnosticFloatingHint = {link = "DiagnosticHint"},
  DiagnosticSignHint = {link = "DiagnosticHint"},
  DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
  DiagnosticInfo = {fg = "#71b4d6"},
  DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
  DiagnosticSignInfo = {link = "DiagnosticInfo"},
  DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
  DiagnosticOk = {fg = "#7ec97e"},
  DiagnosticFloatingOk = {link = "DiagnosticOk"},
  DiagnosticSignOk = {link = "DiagnosticOk"},
  DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
  DiagnosticUnderlineError = {sp = "#f16e65", undercurl = true},
  DiagnosticUnderlineHint = {sp = "#7ec9a3", underline = true},
  DiagnosticUnderlineInfo = {sp = "#71b4d6", underline = true},
  DiagnosticUnderlineOk = {sp = "#7ec97e", underline = true},
  DiagnosticUnderlineWarn = {sp = "#ef934d", undercurl = true},
  DiagnosticWarn = {fg = "#ef934d"},
  DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
  DiagnosticSignWarn = {link = "DiagnosticWarn"},
  DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
  EndOfBuffer = {fg = "#0f0f0f", bg = "#0f0f0f"},
  ErrorMsg = {fg = "#f16e65", bg = "#0f0f0f"},
  FloatBorder = {fg = "#6c756f", bg = "#0f0f0f"},
  FloatTitle = {fg = "#0f0f0f", bg = "#71b4d6", bold = true},
  FoldColumn = {fg = "#6c756f", bg = "#0f0f0f"},
  Folded = {fg = "#d9cdb5", bg = "#2b302b"},
  LineNr = {fg = "#6c756f", bg = "#0f0f0f"},
  LineNrAbove = {link = "LineNr"},
  LineNrBelow = {link = "LineNr"},
  LspCodeLens = {fg = "#6c756f", bg = "#0f0f0f"},
  LspCodeLensSeparator = {link = "LspCodeLens"},
  LspReferenceText = {bg = "#2b302b"},
  LspReferenceRead = {link = "LspReferenceText"},
  LspReferenceWrite = {link = "LspReferenceText"},
  LspSignatureActiveParameter = {fg = "#f4decd", bg = "#2b302b"},
  MatchParen = {fg = "#f4decd", bg = "#2b302b", bold = true},
  ModeMsg = {fg = "#f4decd", bg = "#0f0f0f", bold = true},
  MoreMsg = {fg = "#7ec97e", bg = "#0f0f0f"},
  MsgSeparator = {fg = "#6c756f", bg = "#191b19"},
  NonText = {fg = "#6c756f", bg = "#0f0f0f"},
  NormalFloat = {fg = "#f4decd", bg = "#0f0f0f"},
  Pmenu = {fg = "#f4decd", bg = "#191b19"},
  PmenuKind = {link = "Pmenu"},
  PmenuExtra = {fg = "#d9cdb5", bg = "#191b19"},
  PmenuSbar = {bg = "#191b19"},
  PmenuSel = {fg = "#0f0f0f", bg = "#71b4d6"},
  PmenuExtraSel = {link = "PmenuSel"},
  PmenuKindSel = {link = "PmenuSel"},
  WildMenu = {link = "PmenuSel"},
  PmenuThumb = {bg = "#6c756f"},
  Question = {fg = "#71b4d6", bg = "#0f0f0f"},
  QuickFixLine = {fg = "#0f0f0f", bg = "#71b4d6"},
  Search = {fg = "#0f0f0f", bg = "#d9cdb5"},
  SignColumn = {fg = "#f4decd", bg = "#0f0f0f"},
  SpecialKey = {fg = "#6c756f", bg = "#0f0f0f"},
  SpellBad = {sp = "#f16e65", undercurl = true},
  SpellCap = {sp = "#71b4d6", undercurl = true},
  SpellLocal = {sp = "#7ec97e", undercurl = true},
  SpellRare = {sp = "#e28dc6", undercurl = true},
  StatusLine = {fg = "#f4decd", bg = "#191b19", bold = true},
  StatusLineNC = {fg = "#6c756f", bg = "#191b19"},
  TabLine = {fg = "#f4decd", bg = "#191b19"},
  TabLineFill = {fg = "#6c756f", bg = "#191b19"},
  TabLineSel = {fg = "#0f0f0f", bg = "#71b4d6", bold = true},
  Visual = {fg = "#0f0f0f", bg = "#d9cdb5"},
  VisualNOS = {link = "Visual"},
  WarningMsg = {fg = "#ef934d", bg = "#0f0f0f"},
  Whitespace = {fg = "#6c756f", bg = "#0f0f0f"},
  WinBar = {fg = "#f4decd", bg = "#191b19", bold = true},
  WinBarNC = {fg = "#6c756f", bg = "#191b19"},
  WinSeparator = {fg = "#6c756f", bg = "#0f0f0f"},
  VertSplit = {link = "WinSeparator"},
  -- PATCH_CLOSE
}

-- Plugin-specific overrides kept outside Shipwright's generated region.
colors.MiniPickMatchCurrent = {
  fg = "#0f0f0f",
  bg = "#d9cdb5",
}

colors.MiniPickMatchMarked = {
  fg = "#7ec9a3",
  bg = "#191b19",
}

colors.MiniPickMatchRanges = {
  bold = true,
}

vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.cmd("highlight clear")
vim.g.colors_name = "mine"

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end

-- Match Ghostty's palette in newly opened :terminal buffers.
local terminal_colors = {
  "#0f0f0f", "#f16e65", "#7ec97e", "#ef934d",
  "#71b4d6", "#e28dc6", "#7ec9a3", "#d9cdb5",
  "#6c756f", "#f16e65", "#7ec97e", "#ef934d",
  "#71b4d6", "#e28dc6", "#7ec9a3", "#f4decd",
}

for index, color in ipairs(terminal_colors) do
  vim.g["terminal_color_" .. (index - 1)] = color
end
