# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DFE1F2
background         #202125
cursor             #999DB9

active_tab_foreground     #202125
active_tab_background     #DFE1F2
inactive_tab_foreground   #DFE1F2
inactive_tab_background   #202125

active_border_color   #DFE1F2
inactive_border_color #202125
bell_border_color     #101927

color0      #46484C
color1		#101927
color2		#3F4260
color3		#3F4260
color4		#865B72
color5		#865B72
color6		#7A80A3
color7		#C8CCE4
color8		#8C8F9F
color9		#152234
color10		#545880
color11		#545880
color12		#B37998
color13		#B37998
color14		#A3AAD9
color15		#C8CCE4
