# Mellow colorscheme for wezterm
[colors]
foreground = "#c9c7cd" 
background = "#161617"
cursor_bg = "#c9c7cd" 
cursor_border = "#c9c7cd"
cursor_fg = "#161617" 
selection_bg = "#3c3b3e" 
selection_fg = "#c9c7cd"  
scrollbar_thumb = "#57575f"
split = "#57575f"
ansi = ["#27272a","#ea83a5","#90b99f","#e6b99d","#9ca2cf","#85b5ba","#85b5ba","#c9c7cd"]
brights = ["#353539","#ED96B3","#a7c8b3","#eac5ae","#acb1d7","#b7aed5","#97c0c4","#d3d1d7"]
